I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/insist_furry_route.rpy", line 5, in script
    S "Something sweet about my children [placholder]"
KeyError: u'placholder'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/insist_furry_route.rpy", line 5, in script
    S "Something sweet about my children [placholder]"
  File "renpy/ast.py", line 901, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "renpy/exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "renpy/character.py", line 1240, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "renpy/character.py", line 1159, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "renpy/character.py", line 1139, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "renpy/substitutions.py", line 278, in substitute
    s = formatter.vformat(s, (), kwargs) # type: ignore
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 585, in _vformat
  File "renpy/substitutions.py", line 168, in get_field
    obj, arg_used = super(Formatter, self).get_field(field_name, args, kwargs)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 605, in get_value
KeyError: u'placholder'

Windows-10-10.0.22000 AMD64
Ren'Py 7.5.0.22062402
Mini Jame Gam 11 1.0
Fri Jul  1 18:24:27 2022
